project_id = "npgbotlrokivbuqqzbwm"

[functions.weekly-welfare-deduction]
verify_jwt = true

[functions.create-member]
verify_jwt = false

[functions.send-reminder-email]
verify_jwt = true

[functions.generate-receipt]
verify_jwt = false
